apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
spec:
  selector:
    matchLabels:
      app: greeter
  replicas: 3
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
        - name: greeter
          image: greeter:1.0
          ports:
            - containerPort: 8080
