apiVersion: v1
kind: Service
metadata:
  name: greeter
  labels:
    name: greeter
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: greeter
  type: NodePort
